server.port=8080
spring.application.name=Project Saloon Backend

# Swagger Config
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs



# JWT Secret
jwt.secret=${JWT_SECRET:your_super_secret_jwt_key_saloon_which_must_be_long_enough}
